### ISSUE TITLE
Support CLI arguments containing spaces?

### ISSUE THREAD

**Issue by NateEag** [words/levenshtein-edit-distance#9]
As a heavy Bash user, I expected the CLI to support the standard Bash mechanism of passing strings with spaces in them by using quotes.

However, doing that with version 3.0.0 installed via npm outputs the help message and exits with status 1:

```bash
$ levenshtein-edit-distance "Has Spaces" "Has-No-Spaces" 

  Usage: levenshtein-edit-distance [options] <word> <word>

  Levenshtein edit distance. No cruft. Real fast.

  Options:

    -h, --help           output usage information
    -v, --version        output version number
    -i, --insensitive    ignore casing

  Usage:

  # output distance
  $ levenshtein-edit-distance sitting kitten
  3

  # output distance from stdin
  $ echo "saturday,sunday" | levenshtein-edit-distance
$ echo $?
1
```

Do you have any interest in supporting input containing spaces? 

I've been using the CLI tool to compare filesystem paths for similarity. Having support for spaces would be useful there (I noticed this due to a bug report from a user of an internal tool at `$DAYJOB`).

**Comment by NateEag** [comment]
After a few minutes of poking at `cli.js` in my `node_modules` folder, I came up with a quick patch that shows rough support for the behavior I expected:

```bash
$ levenshtein-edit-distance "Has Spaces" "Has-Spaces" 
1
```

The hack was:

```patch
--- node_modules/levenshtein-edit-distance/cli.bak.js	2021-11-17 15:47:24.000000000 -0500
+++ node_modules/levenshtein-edit-distance/cli.js	2021-11-17 15:47:29.000000000 -0500
@@ -34,7 +34,7 @@
     getDistance(String(data).trim())
   })
 } else {
-  getDistance(argv.join(' '))
+  getDistance(argv.splice(-2, 2))
 }
 
 function help() {
@@ -65,9 +65,7 @@
 /**
  * @param {string} value
  */
-function getDistance(value) {
-  var values = value.split(',').join(' ').split(/\s+/)
-
+function getDistance(values) {
   if (values.length === 2) {
     // @ts-ignore yes, the length is 2.
     console.log(distance(values))
```

I can see that the program also [accepts input on stdin](https://github.com/words/levenshtein-edit-distance/blob/d59e54abe3c88cfc33ba186ec10789f589608066/cli.js#L30). 

Accepting two lines of input on stdin might be an acceptable way to support strings containing spaces. I think you could mostly-preserve backwards compatibility by falling back to splitting on commas if only one line of input is received, but I have not thought that through thoroughly.

**Comment by wooorm** [comment]
Sure, PR welcome!

stdin accepts CSV, I think that should remain supported?

**Comment by NateEag** [comment]
Okay, thanks! I'll look for some time to do a PR.

**Comment by wooorm** [comment]
Closing, but still open to a PR!

**Comment by NateEag** [comment]
Makes sense - obviously I've not managed to do this.

It is in my todo list with the `open-source` tag, but as a father of three small children it's hard to carve out contribution time.
